version: '3'
services:
    db:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: centos
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: centos_db
        ports:
          - "3306:3306"
    web:
        build: .
        ports:
          - "80:80"
          - "8080:8080"
          - "212:22"